#time in seconds for the peace or resource gather phase
peace_time: 1800

#time for the battle phase of the game to last
border_shrink_time: 1800

#How small should the border be?
border_minimum_size: 15

#Border start size
border_start_size: 6000

#Show phase timer?
show_timer: true

#Allow chatting mid-game?
allow_chat_in_match: false

#Multiply damage dealt to combat loggers (Environment damage)
combat_logger_damage_multiplier_environment: 1.5

#Multiply damage dealt to combat loggers (Player damage)
combat_logger_damage_multiplier_player: 10.0

#How long should the combat logger track logouts? (Seconds)
combat_logger_damage_track_time: 10

#World Name, do not change unless your world is not called this
world_name: "world"

#How long should spawn effects last?
spawn_effect_duration: 300

#Text chat proximity radius
chat_radius: 60.0